### PR TITLE
Truly fix the use of libdir for the runtime check

### PR DESCRIPTION
**Pull request by pepeiborra**
The previous change to remove a use of `guessLibdir` accidentally hardcoded the libdir at compile time, which made the check always succeed.

### CODE REVIEW

**Comment by jneira** [comment]
Should i use a branch of ghcide to test it? ghcide master fails with
```
exe\Rules.hs:105:24: error:
    • Couldn't match type ‘FilePath -> IO VersionCheck’
                     with ‘IO VersionCheck’
      Expected type: template-haskell-2.14.0.0:Language.Haskell.TH.Syntax.Q
                       (template-haskell-2.14.0.0:Language.Haskell.TH.Syntax.TExp
                          (IO VersionCheck))
        Actual type: template-haskell-2.14.0.0:Language.Haskell.TH.Lib.Internal.TExpQ
                       (FilePath -> IO VersionCheck)
    • In the expression: makeGhcVersionChecker (pure <$> getLibdir)
      In the Template Haskell splice
        $$(makeGhcVersionChecker (pure <$> getLibdir))
      In the expression: $$(makeGhcVersionChecker (pure <$> getLibdir))
    |
105 | ghcVersionChecker = $$(makeGhcVersionChecker (pure <$> getLibdir))
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal.exe: Failed to build exe:ghcide from ghcide-0.1.0. See the build log
```
and not sure how to test that without ghcide (with an adhoc executable using as a library or ghci?)

**Comment by jneira** [comment]
Well, i am simply patching ghcide to test it following the code example...:
```diff
diff --git a/exe/Rules.hs b/exe/Rules.hs
index 9ae1b23..be0bcb6 100644
--- a/exe/Rules.hs
+++ b/exe/Rules.hs
@@ -101,12 +101,13 @@ getComponentOptions cradle = do
         -- That will require some more changes.
         CradleNone      -> fail "'none' cradle is not yet supported"

-ghcVersionChecker :: IO VersionCheck
+ghcVersionChecker :: FilePath -> IO VersionCheck
 ghcVersionChecker = $$(makeGhcVersionChecker (pure <$> getLibdir))

 checkGhcVersion :: IO (Maybe HscEnvEq)
 checkGhcVersion = do
-    res <- ghcVersionChecker
+    libdir <- getLibdir
+    res <- ghcVersionChecker libdir
     case res of
         Failure err -> do
           putStrLn $ "Error while checking GHC version: " ++ show err
```

**Comment by jneira** [comment]
I don't see the specific error in ghcide, maybe my patch is incorrect.
I've print the value of `getLibdir` in ghcide and it is always the ghc used (if you dont set `$NIX_GHC_LIBDIR` ) to compile ghcide, independently of the ghc in path or the used one to compile the project with both cabal or stack (so the check always hold)

To get the real ghc used ghcide should call at runtime `ghc --numeric-version`, in the context of cabal or stack if possible, right?

If i set `$NIX_GHC_LIBDIR` to the actual project ghc libdir, it works so i guess this patch works standalone:
```
PS D:\dev\ws\haskell\cabal-test> $env:NIX_GHC_LIBDIR="D:\bin\stack\x86_64-windows\ghc-8.8.3\lib\"
PS D:\dev\ws\haskell\cabal-test> ghc --print-libdir
D:\bin\stack\x86_64-windows\ghc-8.8.3\lib
PS D:\dev\ws\haskell\cabal-test> ghcide
ghcide version: 0.1.0 (GHC: 8.6.5) (PATH: D:\bin\ghcide.exe)
Ghcide setup tester in D:\dev\ws\haskell\cabal-test.
Report bugs at https://github.com/digital-asset/ghcide/issues
Ghc libdir:D:\bin\stack\x86_64-windows\ghc-8.8.3\lib\

Step 1/6: Finding files to test in D:\dev\ws\haskell\cabal-test
Found 2 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Loading D:\dev\ws\haskell\cabal-test\hie.yaml

Step 4/6, Cradle 1/1: Loading GHC Session
> Build profile: -w ghc-8.8.3 -O1
> In order, the following will be built (use -v for more details):
>  - cabal-test-0.1.0.0 (lib) (first run)
> Preprocessing library for cabal-test-0.1.0.0..

Step 5/6: Initializing the IDE

Step 6/6: Type checking the files
File:     D:\dev\ws\haskell\cabal-test\app\Main.hs
Hidden:   no
Range:    1:0-100001:0
Source:   compiler
Severity: DsError
Message:
  ghcide compiled against GHC 8.6.5 but currently using 8.8.3 . This is unsupported, ghcide must be
  compiled with the same GHC version as the project.
  CallStack (from HasCallStack):
  error, called at src\Development\IDE\GHC\Util.hs:175:17 in
  ghcide-0.1.0-9f2305b22ee949d6b27ee25fd4dc918afe395f9d:Development.IDE.GHC.Util
File:     D:\dev\ws\haskell\cabal-test\src\Lib.hs
Hidden:   no
Range:    1:0-100001:0
Source:   compiler
Severity: DsError
Message:
  ghcide compiled against GHC 8.6.5 but currently using 8.8.3 . This is unsupported, ghcide must be
  compiled with the same GHC version as the project.
  CallStack (from HasCallStack):
  error, called at src\Development\IDE\GHC\Util.hs:175:17 in
  ghcide-0.1.0-9f2305b22ee949d6b27ee25fd4dc918afe395f9d:Development.IDE.GHC.Util
Files that failed:
 * D:\dev\ws\haskell\cabal-test\app\Main.hs
 * D:\dev\ws\haskell\cabal-test\src\Lib.hs
```

**Comment by pepeiborra** [comment]
Your patch to ghcide is correct.

I expected `getLibDir` to return the libdir for the GHC in the run-time path. It certainly does in my case, but maybe that's not always true. 

Perhaps when using both Nix and stack, there are two potential GHCs around, and `getLibdir` picks the "wrong" one. If that happens, I expect that the ghc-check will succeed but building the project might fail with missing dependencies, but this would be an independent ghcide bug.

**Comment by jneira** [comment]
> I expected getLibDir to return the libdir for the GHC in the run-time path

I dont use nix and i've tried to build ghcide with cabal and stack, just in case.

I've take a look to `ghc-paths` and i dont see how could it retrieve the libdir at runtime, tbh. It uses CPP and set the value to 'GHC_PATHS_LIBDIR`. Afaiu it sets the value at compile time (but maybe i am wrong) 🤔

**Comment by pepeiborra** [comment]
That's right, `ghc-paths` records the path to a GHC libdir at compile time. Since a `ghc-paths` package installation is part of a GHC installation, this is always what you want. Nix does create a new GHC installation for every derivation, and therefore it needs to patch `ghc-paths` or use an env var.

Schematically:

### GHC ct (compile-time)
  - used to build *ghcide*
  - `version(ct)` determined by querying the package database.
  - package database is queried using the GHC api, which requires a GHC libdir.
  - `libdir(rt)` provided by the caller. 
  - *ghcide* finds `libdir(rt)` by calling `GHC.Paths.libdir`

### GHC rt (run-time)
  - used to build the user project. *ghcide* needs its libdir to drive the GHC api
  - `version(rt)` determined by calling `ghc --numeric-version` but first we need the path to `ghc`.
  - `path(rt)` determined from the libdir by making assumptions on the layout of GHC installation
  - `libdir(rt)` provided by the caller
  - *ghcide* finds `libdir(rt)` by calling `GHC.Paths.libdir`

**Comment by jneira** [comment]
Thanks for the info. However i still dont know why it doesn't work for me, could it be a windows issue?

**Comment by pepeiborra** [comment]
I don't know, it could be anything. Does ghcide manage to load your project at all when mixing up ghc versions, or does it fail?

**Comment by jneira** [comment]
It fails due to missing base version:

```
PS D:\dev\ws\haskell\cabal-test> ghcide
ghcide version: 0.1.0 (GHC: 8.6.5) (PATH: D:\bin\ghcide.exe)
Ghcide setup tester in D:\dev\ws\haskell\cabal-test.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in D:\dev\ws\haskell\cabal-test
Found 2 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Loading D:\dev\ws\haskell\cabal-test\hie.yaml

Step 4/6, Cradle 1/1: Loading GHC Session
> Build profile: -w ghc-8.8.3 -O1
> In order, the following will be built (use -v for more details):
>  - cabal-test-0.1.0.0 (lib) (first run)
> Preprocessing library for cabal-test-0.1.0.0..
ghcide.exe: <command line>: cannot satisfy -package-id base-4.13.0.0
    (use -v for more information)
```

**Comment by pepeiborra** [comment]
You are right, I was confused by how `getLibdir` works in nix, which patches `ghc-paths`. In non nix environments, `getLibdir` always returns the compile-time libdir, and ghc-check 0.4 doesn't do anything useful out of the box.

The only option I see is to use the previous approach to determine the runtime version, which relies on the ghc pkg database. The problem with that approach is that it only works if the pkg database can be loaded, which is often not the case across ghc versions - but hopefully ghc-check can detect this and produce a useful error message.

Back to the drawing board...

**Comment by pepeiborra** [comment]
I'm merging this PR and will open a new one once I have something

**Pull request merged**
