### PR TITLE
Use multiple strategies for detecting ghc mismatches

### LINKED ISSUE #6: makeGhcVersionChecker fails to detect the runtime version in non nix systems
ghc-check 0.3.0 introduced a new method to find the runtime ghc version, which relies on querying the ghc executable found via the libdir. 

In 0.3.0 the libdir is obtained via `guessLibDir` which only find the runtime libdir in Nix systems. In all other systems it will find the compile-time libdir, and thus render the check ineffectful as discussed in #5 

This has been fixed in HEAD, where the libdir is provided by the caller. But this doesn't really help, as there isn't anything the caller can do to conjure the libdir that corresponds to the package database being loaded. Thus, the approach of querying the ghc executable is not viable.

This means we are back to querying the runtime package database:
- Querying the version of the ghc package only works if said package is registered, which is not always the case.
- Querying the version of base doesn't work as base is not bumped in every ghc minor release
- The abi of the base package does seem to be unique across ghc versions, but will lead to meaningless  "mismatch" error messages

### PR DESCRIPTION
**Pull request by pepeiborra**
Check the runtime ghc installation,
the runtime ghc package version,
and the base package abi version

Fixes #6

### CODE REVIEW

**Comment by pepeiborra** [comment]
@jneira I have tested on Nixpkgs (Ubuntu). Could you give it a go in Windows? The corresponding ghcide branch is https://github.com/pepeiborra/ghcide/tree/ghc-check-more-fixes

**Comment by pepeiborra** [comment]
Tested successfully in Mac Os using stack, no Nix involved at all

**Comment by jneira** [comment]
It seems it does not work for me in windows+cabal.:

```console
PS D:\dev\ws\haskell> cd ghc-check
PS D:\dev\ws\haskell\ghc-check> git status
On branch multi
Your branch is up to date with 'origin/multi'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ghc-check.cabal

no changes added to commit (use "git add" and/or "git commit -a")
PS D:\dev\ws\haskell\ghc-check> git pull
index efb4b90..7a36e6c 100644
+++ b/ghc-check.cabal
@@ -1,7 +1,7 @@
 cabal-version:       1.20
 build-type:          Simple
 name:                ghc-check
-version:             0.3.0.1
+version:             0.4.0.0
PS D:\dev\ws\haskell\ghc-check>
PS D:\dev\ws\haskell\ghc-check> ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.8.3
PS D:\dev\ws\haskell\ghc-check> cd ..
PS D:\dev\ws\haskell> cd ghcide
PS D:\dev\ws\haskell\ghcide> cat .\cabal.project
packages: ../ghc-check .
PS D:\dev\ws\haskell\ghcide> cabal install
Wrote tarball sdist to
D:\dev\ws\haskell\ghcide\dist-newstyle\sdist\ghc-check-0.4.0.0.tar.gz
D:\dev\ws\haskell\ghcide\dist-newstyle\sdist\ghcide-0.1.0.tar.gz
PS D:\dev\ws\haskell\ghcide> git status
Your branch is up to date with 'pepe/ghc-check-more-fixes'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        cabal.project

nothing added to commit but untracked files present (use "git add" to track)
PS D:\dev\ws\haskell\ghcide> ghcide --version
ghcide version: 0.1.0 (GHC: 8.8.3) (PATH: D:\bin\ghcide.exe)
PS D:\dev\ws\haskell\ghcide> cd ..
PS D:\dev\ws\haskell> cd cabal-test
PS D:\dev\ws\haskell\cabal-test> $env:PATH="D:\bin\stack\x86_64-windows\ghc-8.6.5\bin;$env:PATH"
PS D:\dev\ws\haskell\cabal-test> ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
PS D:\dev\ws\haskell\cabal-test> ghcide .
ghcide version: 0.1.0 (GHC: 8.8.3) (PATH: D:\bin\ghcide.exe)
Ghcide setup tester in D:\dev\ws\haskell\cabal-test.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in D:\dev\ws\haskell\cabal-test
Found 2 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Loading D:\dev\ws\haskell\cabal-test\hie.yaml

Step 4/6, Cradle 1/1: Loading GHC Session
> Resolving dependencies...
> Build profile: -w ghc-8.6.5 -O1
> In order, the following will be built (use -v for more details):
>  - cabal-test-0.1.0.0 (lib) (first run)
> Configuring library for cabal-test-0.1.0.0..
> Preprocessing library for cabal-test-0.1.0.0..
ghcide.exe: <command line>: cannot satisfy -package-id base-4.12.0.0
    (use -v for more information)
```

**Comment by jneira** [comment]
With stack neither:

```console
PS D:\dev\ws\haskell\stack-test> cat .\stack.yaml
resolver: lts-14.27 # Last ghc-8.6.5 lts

packages:
- .
PS D:\dev\ws\haskell\stack-test> ghcide .
ghcide version: 0.1.0 (GHC: 8.8.3) (PATH: D:\bin\ghcide.exe)
Ghcide setup tester in D:\dev\ws\haskell\stack-test.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in D:\dev\ws\haskell\stack-test
Found 3 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Implicit cradle for D:\dev\ws\haskell\stack-test
Cradle {cradleRootDir = "D:\\dev\\ws\\haskell\\stack-test", cradleOptsProg = CradleAction: Stack}

Step 4/6, Cradle 1/1: Loading GHC Session
> Using main module: 1. Package `stack-test' component stack-test:exe:stack-test with main-is file: D:\dev\ws\haskell\sta
ck-test\app\Main.hs
> Building all executables for `stack-test' once. After a successful build of all of them, only specified executables wil
l be rebuilt.
> stack-test> configure (lib + exe)
> Configuring stack-test-0.1.0.0...
> stack-test> initial-build-steps (lib + exe)
> Configuring GHCi with the following packages: stack-test
> D:\dev\ws\haskell\stack-test\.stack-work\install\482bee08\pkgdb;C:\sr\snapshots\c2ec28a9\pkgdb;D:\bin\stack\x86_64-windows\ghc-8.6.5\lib\package.conf.d
ghcide.exe: addLibrarySearchPath: D:\bin\stack\x86_64-windows\ghc-8.8.3\lib\base-4.12.0.0 (Win32 error 2): El sistema no puede encontrar el archivo especificado.
ghcide.exe: <command line>: addDLL: HSbase-4.12.0.0 or dependencies not loaded. (Win32 error 126)
```

**Comment by pepeiborra** [comment]
There is something wrong with your test, I would expect `ghcide` to print the git hash at startup, e.g.:
(scroll all the way to the right)
```
[nix-shell:~/scratch/ghcide]$ dist-newstyle/build/x86_64-linux/ghc-8.10.1/ghcide-0.1.0/x/ghcide/build/ghcide/ghcide src/Development/IDE/Plugin
ghcide version: 0.1.0 (GHC: 8.10.1) (PATH: /home/pepe/scratch/ghcide/dist-newstyle/build/x86_64-linux/ghc-8.10.1/ghcide-0.1.0/x/ghcide/build/ghcide/ghcide) (GIT hash: 39c92832d7ac86b7c6e241fb20d64ccc7c1fc75b)
Ghcide setup tester in /home/pepe/scratch/ghcide.
Report bugs at https://github.com/digital-asset/ghcide/issues
...
```

**Comment by jneira** [comment]
I am afraid gitrev does not work (for me at least) if you installs the executable with cabal: https://github.com/acfoltzer/gitrev/issues/23#issuecomment-618697750

I've added some traces to ghc-check in case they could help:
```
PS D:\dev\ws\haskell\cabal-test> ghcide .
ghcide version: 0.1.0 (GHC: 8.8.3) (PATH: D:\bin\ghcide.exe)
Ghcide setup tester in D:\dev\ws\haskell\cabal-test.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in D:\dev\ws\haskell\cabal-test
Found 2 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Loading D:\dev\ws\haskell\cabal-test\hie.yaml

Step 4/6, Cradle 1/1: Loading GHC Session
> Build profile: -w ghc-8.6.5 -O1
> In order, the following will be built (use -v for more details):
>  - cabal-test-0.1.0.0 (lib) (first run)
> Preprocessing library for cabal-test-0.1.0.0..
checkGhcVersion:  trackedPackages = ["ghc","base"], compileTimeVersions = [("ghc",PackageVersion {myVersion = MyVersion (Version {versionBranch = [8,8,3], versionTags = []}), abi = "4b364c94a5b462b0ec10e203d4827f02"}),("base",PackageVersion {myVersion = MyVersion (Version {versionBranch = [4,13,0,0], versionTags = []}), abi = "76efabad708168fdf7e44222218b8976"})], runtimeLibdir = D:\\bin\\stack\\x86_64-windows\\ghc-8.8.3\\lib
checkGhcVersion: compileTime = Version {versionBranch = [8,8,3], versionTags = []}, runTime = Version {versionBranch = [8,8,3], versionTags = []}
ghcide.exe: <command line>: cannot satisfy -package-id base-4.12.0.0
    (use -v for more information)
PS D:\dev\ws\haskell\cabal-test> 
```

**Comment by pepeiborra** [comment]
Thanks, that helps.

My guess is that the error comes from hie-bios, which must run before ghcide can start the ghc-api session and do the second stage of the ghc-check.  Can you share the hie-bios cradle and the Cabal descriptor used in your `cabal-test` project?

**Comment by pepeiborra** [comment]
Or alternatively, use the `hie-bios` command line directly to validate that cradle loading succeeds.

**Comment by jneira** [comment]
Sure, the cradle seems to be ok:
```console
PS D:\dev\ws\haskell\cabal-test> hie-bios debug .\src\Lib.hs
Root directory:      D:\dev\ws\haskell\cabal-test
Component directory: D:\dev\ws\haskell\cabal-test
GHC options:         -fbuilding-cabal-package -O0 -outputdir D:\dev\ws\haskell\cabal-test\dist-newstyle\build\x86_64-windows\ghc-8.6.5\cabal-test-0.1.0.0\build -odir D:\dev\ws\haskell\cabal-test\dist-newstyle\build\x86_64-windows\ghc-8.6.5\cabal-test-0.1.0.0\build -hidir D:\dev\ws\haskell\cabal-test\dist-newstyle\build\x86_64-windows\ghc-8.6.5\cabal-test-0.1.0.0\build -stubdir D:\dev\ws\haskell\cabal-test\dist-newstyle\build\x86_64-windows\ghc-8.6.5\cabal-test-0.1.0.0\build -i -iD:\dev\ws\haskell\cabal-test\dist-newstyle\build\x86_64-windows\ghc-8.6.5\cabal-test-0.1.0.0\build -isrc -iD:\dev\ws\haskell\cabal-test\dist-newstyle\build\x86_64-windows\ghc-8.6.5\cabal-test-0.1.0.0\build\autogen -iD:\dev\ws\haskell\cabal-test\dist-newstyle\build\x86_64-windows\ghc-8.6.5\cabal-test-0.1.0.0\build\global-autogen -ID:\dev\ws\haskell\cabal-test\dist-newstyle\build\x86_64-windows\ghc-8.6.5\cabal-test-0.1.0.0\build\autogen -ID:\dev\ws\haskell\cabal-test\dist-newstyle\build\x86_64-windows\ghc-8.6.5\cabal-test-0.1.0.0\build\global-autogen -ID:\dev\ws\haskell\cabal-test\dist-newstyle\build\x86_64-windows\ghc-8.6.5\cabal-test-0.1.0.0\build -optP-include -optPD:\dev\ws\haskell\cabal-test\dist-newstyle\build\x86_64-windows\ghc-8.6.5\cabal-test-0.1.0.0\build\autogen\cabal_macros.h -this-unit-id cabal-test-0.1.0.0-inplace -hide-all-packages -Wmissing-home-modules -no-user-package-db -package-db C:\sd\ghc-8.6.5\package.db -package-db D:\dev\ws\haskell\cabal-test\dist-newstyle\packagedb\ghc-8.6.5 -package-db D:\dev\ws\haskell\cabal-test\dist-newstyle\build\x86_64-windows\ghc-8.6.5\cabal-test-0.1.0.0\package.conf.inplace -package-id base-4.12.0.0 -package-id bytestring-0.10.8.2 -XHaskell2010 Lib -hide-all-packages
System libraries:    D:\bin\stack\x86_64-windows\ghc-8.6.5\lib
Config Location:     D:\dev\ws\haskell\cabal-test\hie.yaml
Cradle:              Cradle {cradleRootDir = "D:\\dev\\ws\\haskell\\cabal-test", cradleOptsProg = CradleAction: Cabal}       
Dependencies:        cabal-test.cabal cabal.project cabal.project.local
```

I have to note that i added another trace that it is not shown, in the code i think should do the final check:

```haskell
return $ if runTime /= compileTime
    then InstallationMismatch{..}
    else InstallationChecked $ do
      runTimeVersions <- collectPackageVersions trackedPackages
      let compares =
            Map.intersectionWith
              comparePackageVersions
              compileTimeVersionsMap
              (Map.fromList runTimeVersions)
          mismatches = Map.mapMaybe id compares
      traceM $ "checkGhcVersion: compares = " ++ show compares 
      return
        $ getFirst
        $ foldMap
          (\p -> First $ (p,) <$> Map.lookup p mismatches)
          trackedPackages
```

**Comment by pepeiborra** [comment]
Can you share the Cabal file as well as the `hie.yaml` file?

**Comment by jneira** [comment]
Sure, although they are quite regular:
* cabal-test.cabal
```
cabal-version:       >=1.10
name:                cabal-test
version:             0.1.0.0
license:             BSD3
license-file:        LICENSE
author:              jneira
maintainer:          atreyu.bbb@gmail.com
build-type:          Simple
extra-source-files:  CHANGELOG.md

library
  exposed-modules:     Lib
  build-depends:       base >=4.12 && <4.15
                     , bytestring
  hs-source-dirs:      src
  default-language:    Haskell2010

executable cabal-test
  main-is:             Main.hs
  build-depends:       base >=4.12 && <4.15
                     , cabal-test
                     , bytestring
  hs-source-dirs:      app
  default-language:    Haskell2010
```
* hie.yaml
```
cradle:
  cabal:
    - path: "./"
      component: "lib:cabal-test"
```

**Comment by pepeiborra** [comment]
Thanks, I can reproduce your results now. I was testing ghcide 8.8 with an 8.10 stack cradle, which seems to be the only combination where the check is effective:

cradle/ghcide | 8.6 | 8.8 | 8.10
--------------|-----|----|---
Cabal 8.6   | success | [fail](http:// "ghcide: <command line>: cannot satisfy -package-id base-4.12.0.0'")  |  [fail](http:// "ghcide: <command line>: cannot satisfy -package-id base-4.12.0.0'") 
Cabal 8.8   | [fail](http:// "ghcide: <command line>: cannot satisfy -package-id base-4.13.0.0'")  | success | [fail](http:// "ghcide: <command line>: cannot satisfy -package-id base-4.13.0.0'") 
Cabal 8.10 | [fail](http:// "ghcide: <command line>: cannot satisfy -package-id base-4.14.0.0'")  | [fail](http:// "ghcide: <command line>: cannot satisfy -package-id base-4.14.0.0'") | success
Stack 8.6   | success | [fail](http:// "ghcide: ghcide: unable to load package `ghc-prim-0.5.3'") | check
Stack 8.8   | check | success | check
Stack 8.10 | check | check | success

`fail` means that the check did not detect the issue (or got a chance to run).

**Comment by pepeiborra** [comment]
Both stack and cabal flag-sets (observable via `hie-bios flags`) include a set of `-package` flags that pin down the set of package dependencies, and a set of `-package-db` flags that add several package databases to the scope. In both cases, the global package database is kept in the scope.

The crucial difference is that stack explicitly adds the package database that comes bundled with ghc into the scope, for the ghc installation that stack sets up for the project. This enables ghcide to set up the ghc api `Session` successfully and run the ghc check, which can then notice the package version mismatches. In the Cabal case, the ghc api `Session` setup fails, because some of those `-package-id` constraints that reference ghc-bundled packages cannot be satisfied.

**Comment by pepeiborra** [comment]
I don't see a reasonable approach to handle the Cabal scenario in ghc-check. It would need to parse the ghc options and query the package databases manually, which duplicates what ghc itself already does.

A more sensible solution is to add exception handling to the ghc `Session` set up in ghcide, in order to produce a more user friendly message. 

The ghcide 8.8 / stack 8.6 failure is an outlier but easy to explain. Even if the global package from the target ghc version (8.6 in this case) are in scope, it's not always the case that the ghc api in ghcide (8.8 in this case) is able to load them, because datatype definitions and/or binary formats may have changed incompatibly. This case should be covered by the exception handling mentioned above, as the error would arise during the ghc `Session` setup too.

**Comment by pepeiborra** [comment]
I have updated the ghcide branch with the exception handling described above and checked again. It covers all the cases except for the stack outlier, getting closer!

cradle/ghcide | 8.6 | 8.8 | 8.10
--------------|-----|----|---
Cabal 8.6   | success | friendly fail | friendly fail 
Cabal 8.8   | friendly fail | success | friendly fail  
Cabal 8.10 | friendly fail | friendly fail | success
Stack 8.6   | success | [fail](http:// "ghcide: ghcide: unable to load package `ghc-prim-0.5.3'") | check
Stack 8.8   | check | success | check
Stack 8.10 | check | check | success

**Comment by pepeiborra** [comment]
It looks like the error is coming from the linker and cannot be caught in Haskell. I give up on that one. The full error:
```
ghcide: 
lookupSymbol failed in relocateSection (relocate external)
/Users/pepe/.stack/programs/x86_64-osx/ghc-8.6.5/lib/ghc-8.6.5/ghc-prim-0.5.3/HSghc-prim-0.5.3.o: unknown symbol `_stg_atomicModifyMutVarzh'
ghcide: ghcide: unable to load package `ghc-prim-0.5.3'
```

EDIT: found a way to catch it from Haskell

**Pull request merged**
