### PR TITLE
Add logic for Windows and fix use of guessLibdir

### LINKED ISSUE #2: Unable to guess GHC binary location in Windows
```
Error while checking GHC version: "D:\\\\bin\\\\stack\\\\x86_64-windows\\\\ghc-8.8.3\\\\lib\\bin\\ghc: readCreateProcess: does not exist (No such file or directory)"
```
https://github.com/mpickering/ghcide/pull/32

### PR DESCRIPTION
**Pull request by pepeiborra**
Fixes #2 
/cc @jneira

### CODE REVIEW

**Comment by pepeiborra** [comment]
@jneira it would be great if you could confirm it works for you before I make a Hackage release

**Comment by jneira** [comment]
i'll check it asap

**Comment by jneira** [comment]
In any case i am getting the error [i reported originally](https://github.com/mpickering/ghcide/pull/32#issuecomment-626235387): `Error while checking GHC version: "D:\\\\bin\\\\stack\\\\x86_64-windows\\\\ghc-8.8.3\\\\lib\\bin\\ghc: readCreateProcess: does not exist (No such file or directory)"`, so the pr should have fixed it.

No directly related with the error but not sure how can i trigger the check in first place. 
```
PS D:\dev\ws\haskell\cabal-test> ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.8.3
PS D:\dev\ws\haskell\ghcide> git status                                                                                           On branch master
Your branch is up to date with 'upstream/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        cabal.project

nothing added to commit but untracked files present (use "git add" to track)
PS D:\dev\ws\haskell\ghcide> cat .\cabal.project
packages: .

source-repository-package
    type: git
    location: https://github.com/pepeiborra/ghc-check.git
    tag: e49430fbe83b824e32e4cfedddfb58a57ab30477
PS D:\dev\ws\haskell\ghcide> cabal install -w ghc-8.6.5
Wrote tarball sdist to
D:\dev\ws\haskell\ghcide\dist-newstyle\sdist\ghcide-0.1.0.tar.gz
Wrote tarball sdist to
D:\dev\ws\haskell\ghcide\dist-newstyle\sdist\ghc-check-0.3.0.1.tar.gz
Resolving dependencies...
Up to date
Copying 'ghcide-test-preprocessor.exe'
Copying 'ghcide.exe'
PS D:\dev\ws\haskell\ghcide> cd ..
PS D:\dev\ws\haskell> cd .\cabal-test\
PS D:\dev\ws\haskell\cabal-test> ghcide
ghcide version: 0.1.0 (GHC: 8.6.5) (PATH: D:\bin\ghcide.exe)
Ghcide setup tester in D:\dev\ws\haskell\cabal-test.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in D:\dev\ws\haskell\cabal-test
Found 2 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Loading D:\dev\ws\haskell\cabal-test\hie.yaml

Step 4/6, Cradle 1/1: Loading GHC Session
> Build profile: -w ghc-8.8.3 -O1
> In order, the following will be built (use -v for more details):
>  - cabal-test-0.1.0.0 (lib) (first run)
> Preprocessing library for cabal-test-0.1.0.0..
ghcide.exe: <command line>: cannot satisfy -package-id base-4.13.0.0
    (use -v for more information)
```

So i have ghcide master built with this version of ghc-check and ghc-8.6.5 but i dont get the error in a project built with ghc-8.8.3. Opening the project in vscode has the same result.

With ghcide compiled with ghc-8.8.3 ghcide loads the files as expected:
```
PS D:\dev\ws\haskell\ghcide> cabal install -w ghc-8.8.3
Wrote tarball sdist to
D:\dev\ws\haskell\ghcide\dist-newstyle\sdist\ghcide-0.1.0.tar.gz
Wrote tarball sdist to
D:\dev\ws\haskell\ghcide\dist-newstyle\sdist\ghc-check-0.3.0.1.tar.gz
Resolving dependencies...
Up to date
Copying 'ghcide-test-preprocessor.exe'
Copying 'ghcide.exe'
PS D:\dev\ws\haskell\ghcide> cd ..
PS D:\dev\ws\haskell> cd .\cabal-test\
PS D:\dev\ws\haskell\cabal-test> ghcide
ghcide version: 0.1.0 (GHC: 8.8.3) (PATH: D:\bin\ghcide.exe)
Ghcide setup tester in D:\dev\ws\haskell\cabal-test.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in D:\dev\ws\haskell\cabal-test
Found 2 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Loading D:\dev\ws\haskell\cabal-test\hie.yaml

Step 4/6, Cradle 1/1: Loading GHC Session
> Build profile: -w ghc-8.8.3 -O1
> In order, the following will be built (use -v for more details):
>  - cabal-test-0.1.0.0 (lib) (first run)
> Preprocessing library for cabal-test-0.1.0.0..

Step 5/6: Initializing the IDE

Step 6/6: Type checking the files

Completed (2 files worked, 0 files failed)
```

I've tested ghcide compiled with ghc-8.8.3 and the project with ghc-8.6.5 and the result is similar:
```
ghcide.exe: <command line>: cannot satisfy -package-id base-4.12.0.0
```


I would expect a specific error about mismatched ghc versions in the first test, am i right?

**Comment by pepeiborra** [comment]
Good catch, there should be a mismatch error. The fix for the use of `guessLibdir` in the runtime check is wrong. Second attempt coming...

**Pull request merged**
