### PR TITLE
Add compatibility with GHC 9.2

### PR DESCRIPTION
**Pull request by fendor**

### CODE REVIEW

**Review by pepeiborra — APPROVED** [review]
Thank you! I’ll upload to Hackage when I’m back at my PC

**Comment by fendor** [comment]
No hurry, GHC 9.2 support will take longer than today :)

**Comment by pepeiborra** [comment]
ghc-check 0.5.0.6 is on Hackage

**Comment by Bodigrim** [comment]
As a Hackage trustee I revised earlier releases:
https://hackage.haskell.org/package/ghc-check-0.5.0.4/revisions/
https://hackage.haskell.org/package/ghc-check-0.5.0.5/revisions/

**Pull request merged**
